### ISSUE TITLE
SanitizeSingleQuotes throws an error when migrating in v2

### ISSUE THREAD

**Issue by RonnieTaz** [lulco/phoenix#279]
I was using the package just fine in Version 1.12 but after my update to Version 2 I always get the error : 
```
PHP Fatal error:  Uncaught TypeError: Phoenix\Database\QueryBuilder\MysqlQueryBuilder::sanitizeSingleQuote(): Argument #1 ($input) must be of type string, int given, called in /home/ronnie/osmmas/vendor/lulco/phoenix/src/Database/Qu
eryBuilder/MysqlQueryBuilder.php on line 247 and defined in /home/ronnie/osmmas/vendor/lulco/phoenix/src/Database/QueryBuilder/MysqlQueryBuilder.php:356
Stack trace:
#0 /home/ronnie/osmmas/vendor/lulco/phoenix/src/Database/QueryBuilder/MysqlQueryBuilder.php(247): Phoenix\Database\QueryBuilder\MysqlQueryBuilder->sanitizeSingleQuote()
#1 /home/ronnie/osmmas/vendor/lulco/phoenix/src/Database/QueryBuilder/MysqlQueryBuilder.php(217): Phoenix\Database\QueryBuilder\MysqlQueryBuilder->createColumnDefault()
#2 /home/ronnie/osmmas/vendor/lulco/phoenix/src/Database/QueryBuilder/MysqlQueryBuilder.php(97): Phoenix\Database\QueryBuilder\MysqlQueryBuilder->createColumn()
#3 /home/ronnie/osmmas/vendor/lulco/phoenix/src/Migration/AbstractMigration.php(336): Phoenix\Database\QueryBuilder\MysqlQueryBuilder->createTable()
#4 /home/ronnie/osmmas/vendor/lulco/phoenix/src/Migration/AbstractMigration.php(317): Phoenix\Migration\AbstractMigration->prepareMigrationTableQueries()
#5 /home/ronnie/osmmas/vendor/lulco/phoenix/src/Migration/AbstractMigration.php(67): Phoenix\Migration\AbstractMigration->prepare()
#6 /home/ronnie/osmmas/vendor/lulco/phoenix/src/Command/MigrateCommand.php(49): Phoenix\Migration\AbstractMigration->migrate()
#7 /home/ronnie/osmmas/vendor/lulco/phoenix/src/Command/AbstractRunCommand.php(42): Phoenix\Command\MigrateCommand->runMigration()
#8 /home/ronnie/osmmas/vendor/lulco/phoenix/src/Command/AbstractCommand.php(78): Phoenix\Command\AbstractRunCommand->runCommand()
#9 /home/ronnie/osmmas/vendor/symfony/console/Command/Command.php(291): Phoenix\Command\AbstractCommand->execute()
#10 /home/ronnie/osmmas/vendor/symfony/console/Application.php(989): Symfony\Component\Console\Command\Command->run()
#11 /home/ronnie/osmmas/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#12 /home/ronnie/osmmas/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#13 /home/ronnie/osmmas/vendor/lulco/phoenix/bin/phoenix(35): Symfony\Component\Console\Application->run()
#14 /home/ronnie/osmmas/vendor/bin/phoenix(97): include('...')
#15 {main}
  thrown in /home/ronnie/osmmas/vendor/lulco/phoenix/src/Database/QueryBuilder/MysqlQueryBuilder.php on line 356
```
This happens for both MySQL and PGSQL migrations. Is the problem my machine or is the library bugged?

**Comment by lulco** [comment]
Hi, thanks for your report. Version 2 is more strict then previous. Could you provide some failing test case or at least describe the column which is problematic? What is the column type and column settings - especially default value.

**Comment by RonnieTaz** [comment]
I found the error, it's the default value that was set to int. Thanks for the help.
